#!/bin/sh

# Visual Studio Code embeds Chromium through Electron and requires the same
# container sandbox workaround as the standalone browser.
exec /usr/bin/code \
    --disable-gpu \
    --disable-software-rasterizer \
    "$@"
